name: 'Radiant Export'
description: 'Run Radiant Export'
inputs:
  RDF:
    description: 'path to rdf file'
    required: true

runs:
  using: "composite"
  steps:
    - run: pnmainc ${{ github.action_path }}/export.tcl ${{ inputs.RDF }}
      shell: bash
